### PR TITLE
Update all typography components to be display: block as per the implementation spec

### PR DESCRIPTION
**Pull request by kevinbarabash**
This diff adds a "display: block" to all components in wonder-blocks-typography
and updates the storybook stories for that component to show that the components
are actually using block style.  It does not modify the Text component which is
still inline.  Lastly, the .babelrc files were updated to transform the object
spread operator.

Reviewers: alex briangenisio

### CODE REVIEW

**Comment by jeresig** [comment]
Just a heads-up: it looks like package-lock.json hasn't been re-generated.

Is this a safe change to roll-out? Everyone is expecting this components to already be block?

**Comment by kevinbarabash** [comment]
It looks like it will cause issues in at least one place. :(

**Comment by jeresig** [comment]
@kevinbarabash How important is it that this be display block? What are we gaining from it? Is this something that people are going to have to frequently work around? It's especially confusing because a bunch of the components that we have right now are actually `<span>`s. Maybe it'd make more sense to just change those to be `div`s and then let people override them with a `span` if they want them to be inline for some reason?

**Comment by kevinbarabash** [comment]
Hmm... it looks like the one place I thought it would be a problem is setting `display: block` manually.

I think it is important as people will end up having to set `display: block` a lot.

**Comment by kevinbarabash** [comment]
> Maybe it'd make more sense to just change those to be divs and then let people override them with a span if they want them to be inline for some reason?

That's one option for implementation this change, but changing the default may still affect some call sites.  I'll just check all of the call sites, but I think this change will be okay.

**Comment by kevinbarabash** [comment]
I forgot to regenerate the snapshots, d'oh.

**Comment by kevinbarabash** [comment]
I'd rather be explicit about styling as opposed to relying on browser defaults for styling of certain tags.

**Comment by kevinbarabash** [comment]
@jeresig I'm guessing the screen readers will read it different.

**Comment by jeresig** [comment]
@kevinbarabash Nope! As far as I can tell screen readers will read both of them completely the same, it's purely from a semantic level (having spans, which are inline by default, behave as a block doesn't make sense).

**Comment by kevinbarabash** [comment]
> having spans, which are inline by default, behave as a block doesn't make sense

Gotcha.  Sorry for not changing this before merging this diff.  It seems low priority, but we should fix it.

**Pull request merged**
