### PR TITLE
Add style and dropdownStyle props to BirthdayPicker

### PR DESCRIPTION
**Pull request by dmcalpin**
## Summary:
To allow the BirthdayPicker to be rendered in a wider variety of locations, such as narrow modals or mobile views, two new props have been added. "style" which allows the caller to add styles to the root element of the BirthdayPicker, and "dropdownStyle" which applies styles to the individual dropdowns. As opposed to a more narrow approach of specifying a "vertical" prop, this broad approach relieves the component of having to know when to render horizontally or vertically. This logic is placed in the callers hands, which can easily be determined via media query.

Issue: None

## Test plan:
- View http://localhost:6061/?path=/story/packages-birthdaypicker--birthday-picker-vertical
- ensure component displays in a top to bottom manner
- View http://localhost:6061/?path=/story/packages-birthdaypicker--birthday-picker-vertical-with-error
- ensure component displays in the same manner, with an error message
- reran unit tests, ensure they pass

### CODE REVIEW

**Comment by dmcalpin** [comment]
Screenshot 2024-08-06 at 3 26 40 PM
Screenshot 2024-08-06 at 3 26 57 PM
Screenshot 2024-08-06 at 3 26 49 PM

**Review by jeresig — APPROVED** [review]
Great - thank you for adding this! Could you add the new props to `__docs__/wonder-blocks-birthday-picker/birthday-picker.argtypes.ts` so that they show up in the Storybook docs? You can see an example of a `style` prop in `__docs__/wonder-blocks-form/text-field.argtypes.ts`. Thanks!

**Review by evanchaney — APPROVED** [review]
🙌 🙌

**Comment by dmcalpin** [comment]
Added:
Screenshot 2024-08-08 at 11 11 16 AM

**Comment by dmcalpin** [comment]
@jeresig it looks like I'm unable to merge this PR because "UI Review" and "UI Tests" are still pending. How does one get those resolved

**Review by beaesguerra — APPROVED** [review]
Thanks for making these changes, it makes the BirthdayPicker more flexible! 🎉 

On a side note, we have a separate ticket (WB-1739) to improve the responsiveness of the BirthdayPicker as I noticed the same issue in other places too! I think this is a good first step before we address it more globally 👍

**Comment by jeresig** [comment]
@dmcalpin oops - all done!

**Pull request merged**
