### PR TITLE
Fix select box docs

### PR DESCRIPTION
**Pull request by somewhatabstract**
This fixes the select-box.md so that the snapshots generate correct code.

### CODE REVIEW

**Comment by jeresig** [comment]
Deploy preview for *wonder-blocks* ready!

Built with commit 1c8ee65cf4aebf15dd518fcda2993e5b40036031

https://deploy-preview-160--wonder-blocks.netlify.com

**Comment by wishdasher** [comment]
Could you also update `package.json` with the `layout` package?

**Comment by somewhatabstract** [comment]
@wishdasher Does it need it? Since this is only test docs, I don't think we need to put a package dep on there.

**Comment by wishdasher** [comment]
Oops, good point. I got confused.

**Pull request merged**
