### PR TITLE
test change to README.md

### PR DESCRIPTION
**Pull request by kevinbarabash**

### CODE REVIEW

**Comment by kevinbarabash** [comment]
[clabot:check]

**Comment by jeresig** [comment]
Deploy preview for *wonder-blocks* ready!

Built with commit ec3716c6f5f26acda1809ca650e28cf208359fe9

https://deploy-preview-557--wonder-blocks.netlify.com

**Comment by kevinbarabash** [comment]
[clabot:check]

**Comment by kevinbarabash** [comment]
[clabot:check]

**Comment by kevinbarabash** [comment]
[clabot:check]

**Comment by kevinbarabash** [comment]
[clabot:check]

**Comment by kevinbarabash** [comment]
[clabot:check]

**Comment by kevinbarabash** [comment]
[clabot:check]

**Pull request closed without merging**
