### PR TITLE
Add "light red" to available wonder blocks colors

### PR DESCRIPTION
**Pull request by jsatk**
This color is currently used in the struggling indicator in webapp.

See: https://github.com/Khan/webapp/blob/ddf131365eb7823a00da5944ad559b872e9018c8/javascript/mastery-package/struggling-indicator.jsx#L35

### CODE REVIEW

**Comment by jeresig** [comment]
Deploy preview for *wonder-blocks* ready!

Built with commit 9ad5f0ccbe425f2dbe044150b0ee08f2f94da3f6

https://deploy-preview-105--wonder-blocks.netlify.com

**Comment by kevinbarabash** [comment]
Going to bring this up during the wonder-blocks sync before making a decision.

**Comment by jsatk** [comment]
Thank you!

**Comment by kevinbarabash** [comment]
We've decided to limit the use of light pink/coral to mastery.  Once we have a better colour we might look at moving that colour into wonder-blocks.

**Comment by jsatk** [comment]
Excellent. Thank you!

**Pull request closed without merging**
