### PR TITLE
add more code owners

### PR DESCRIPTION
**Pull request by kevinbarabash**
The goal of this PR is encourage code ownership by automatically adding people to PRs for changes to wonder-blocks packages that they worked on.

### CODE REVIEW

**Comment by jeresig** [comment]
Deploy preview for *wonder-blocks* ready!

Built with commit a82ca8e88596587f2e444f6cc8cf407916aa6f3c

https://deploy-preview-178--wonder-blocks.netlify.com

**Comment by jeresig** [comment]
Deploy preview for *wonder-blocks* ready!

Built with commit 478293e1e01d3c52c163d119776e3acca07ba542

https://deploy-preview-178--wonder-blocks.netlify.com

**Comment by matchu** [comment]
Cool!

I'm a bit hesitant about being the lead code owner of modals right now. I'm not sure quite what to expect in terms of commitment, and I have a weaker-than-usual grasp of my capacity, since I'm ramping up as Test Prep tech lead and don't really know where that will stabilize in terms of capacity. (I'm also a bit behind on the state of the modals package 😥)

That said, I know review bottlenecks have been an issue in Web Frontend land, and I'd like to be able to contribute to the solution if I can! As a code owner, what should I expect?

**Comment by kevinbarabash** [comment]
@matchu it's really hard to say how much work is involved being a code owner.  A lot of it depends on the package and how many issues arise if any as devs start using the components in `webapp`.  Given your new role as tech lead and the fact that large portions of the modal package being rewritten by @jeresig it probably makes more sense for him to be the code owner for modals.  That being said, we may still ping you if there's some change in the modal portal where we could use your expertise.

**Comment by matchu** [comment]
Okay, thanks all! I'm excited about this project, and I hope I can find a way to pitch in 😊

**Pull request merged**
