### PR TITLE
Fix font.family.sans token

### PR DESCRIPTION
**Pull request by SeanMcP**
## Summary:
There was an issue with the `font.family.sans` token.

Issue: XXX-XXXX

## Test plan:
- Good question

### CODE REVIEW

**Review by jeresig — APPROVED** [review]
Ah, good catch! cc: @jandrade

**Comment by jandrade** [comment]
>Test plan:
> Good question

😆 This could be tested in this story: ?path=/docs/theming-tokens-typography--docs

By making sure that the CSS prop is applied correctly.

https://5e1bf4b385e3fb0020b7073c-mcxpyiegwx.chromatic.com/?path=/docs/theming-tokens-typography--docs#family

@SeanMcP Thanks for catching this! the only missing part before landing this is to add a changeset. To do this, you'll need to run: `yarn changeset`, then mark `tokens` as a patch version and adding a comment specifying the change. That way, our release tooling is capable to publish this change to npm.

More info here: https://khanacademy.atlassian.net/wiki/spaces/WB/pages/2217640195/Versioning+and+releasing+Wonder+Blocks+packages

**Review by jandrade — APPROVED** [review]
🎉 thanks for fixing this!!

**Comment by SeanMcP** [comment]
@jandrade What are the next steps? Just land?

**Comment by jandrade** [comment]
@SeanMcP yeah, land the change and I'll start a release right after that :). And thanks for contributing to Wonder Blocks! 🌯

**Pull request merged**
